-- Seed products from frontend/productInfo.ts as editable catalogue items.
BEGIN;

WITH source_products(slug, name, description, price, image_url, product_info) AS (
  VALUES
    ('bocadillo-atun-millo-mayonesa', 'Bocadillo de atun, millo y mayonesa', 'Bocadillo con ficha alimentaria', 2.50, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80', '{"id":"bocadillo-atun-millo-mayonesa","nombre":"Bocadillo de atun, millo y mayonesa","categoria":"bocadillo","ingredientes":["pan blanco (harina de trigo, agua, levadura, sal)","atun en aceite (atun, aceite de girasol, sal), maiz dulce (maiz, agua, azucar, sal), mayonesa (aceite de soja modificado geneticamente, agua, yema de huevo, jarabe de glucosa y fructosa, vinagre de vino, sal, almidon modificado de maiz e-1422, estabilizante e-415, conservador e-202, acidulante e-270, aroma, conservante e-385 (edta), colorante e-160a)"],"alergenos":["gluten","pescado","soja","huevo"],"trazas":[],"informacionNutricional":{"kcal":275.2,"grasas":6.65,"hidratos":44.51,"azucares":4.17,"proteinas":7.85,"sal":7.14},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT BOCADILLO ATUN JOSE ZERPA.odt","ETIQUETA BOCADILLO ATUN.docx"]}'::jsonb),
    ('bocadillo-jamon', 'Bocadillo de jamon', 'Bocadillo con ficha alimentaria', 2.50, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80', '{"id":"bocadillo-jamon","nombre":"Bocadillo de jamon","categoria":"bocadillo","ingredientes":["pan blanco (harina de trigo, agua, levadura, sal)","fiambre paleta cocida (carne de cerdo y pavo, agua, fecula de patata, sal, proteina de soja y leche, azucar, dextrosa, lactosa, aromas, antioxidante e-316, conservantes e-260, estabilizantes e-407 y e-451, potenciador del sabor e-621, colorante e-120)"],"alergenos":["gluten","soja","leche"],"trazas":["frutos de cascara"],"informacionNutricional":{"kcal":238.4,"grasas":3.36,"hidratos":42.81,"azucares":3.85,"proteinas":8.9,"sal":0.98},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT BOCADILLO DE JAMON JOSE ZERPA.odt","ETIQUETA BOCADILLO JAMON.docx"]}'::jsonb),
    ('bocadillo-jamon-serrano', 'Bocadillo de jamon serrano', 'Bocadillo con ficha alimentaria', 2.50, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80', '{"id":"bocadillo-jamon-serrano","nombre":"Bocadillo de jamon serrano","categoria":"bocadillo","ingredientes":["pan blanco (harina de trigo, agua, levadura, sal)","jamon serrano (jamon de cerdo, sal, azucar, antioxidantes e-331 y e-301, conservadores e-252 y e-250)"],"alergenos":["gluten"],"trazas":[],"informacionNutricional":{"kcal":263.16,"grasas":5.04,"hidratos":40.49,"azucares":3.55,"proteinas":13.3,"sal":1.26},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT BOCADILLO DE JAMON SERRANO JOSE ZERPA.odt","ETIQUETA BOCADILLO DE JAMON SERRANO.docx"]}'::jsonb),
    ('bocadillo-lomo-adobado', 'Bocadillo de lomo adobado', 'Bocadillo con ficha alimentaria', 2.50, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80', '{"id":"bocadillo-lomo-adobado","nombre":"Bocadillo de lomo adobado","categoria":"bocadillo","ingredientes":["pan blanco (harina de trigo, agua, levadura, sal)","lomo adobado (lomo de cerdo 60%, agua, sal, fecula de patata y maiz, dextrosa, estabilizantes e-451 y e-407, proteina de soja, proteina de cerdo, antioxidantes e-331 y e-316, aromas, aroma de humo, especias, potenciador del sabor e-621, conservador e-250)"],"alergenos":["gluten","soja"],"trazas":["leche"],"informacionNutricional":{"kcal":235,"grasas":3.24,"hidratos":41.89,"azucares":3.85,"proteinas":8.76,"sal":1.04},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT BOCADILLO DE LOMO ADOBADO JOSE ZERPA.odt","ETIQUETA BOCADILLO DE LOMO ADOBADO.docx"]}'::jsonb),
    ('bocadillo-pavo-cocido', 'Bocadillo de pavo cocido', 'Bocadillo con ficha alimentaria', 2.50, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80', '{"id":"bocadillo-pavo-cocido","nombre":"Bocadillo de pavo cocido","categoria":"bocadillo","ingredientes":["pan blanco (harina de trigo, agua, levadura, sal)","pechuga de pavo cocida (pechuga de pavo 65%, agua, jarabe de glucosa, dextrosa, cloruro potasico, cloruro sodico, estabilizantes e-451i y e-407, aromas, antioxidante e-301, conservadores e-261 y e-250)"],"alergenos":["gluten"],"trazas":["soja"],"informacionNutricional":{"kcal":228.8,"grasas":2.74,"hidratos":40.75,"azucares":3.71,"proteinas":9.46,"sal":0.82},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT BOCADILLO DE PAVO JOSE ZERPA.odt","ETIQUETA BOCADILLO DE PAVO.docx"]}'::jsonb),
    ('bocadillo-pechuga-plancha', 'Bocadillo de pechuga a la plancha', 'Bocadillo con ficha alimentaria', 2.50, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80', '{"id":"bocadillo-pechuga-plancha","nombre":"Bocadillo de pechuga a la plancha","categoria":"bocadillo","ingredientes":["pan blanco (harina de trigo, agua, levadura, sal)","pechuga de pollo"],"alergenos":["gluten"],"trazas":[],"informacionNutricional":{"kcal":235.8,"grasas":2.99,"hidratos":40.49,"azucares":3.45,"proteinas":10.34,"sal":0.614},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT BOCADILLO DE PECHUGA JOSE ZERPA.odt","ETIQUETA BOCADILLO PECHUGA A LA PLANCHA.docx"]}'::jsonb),
    ('bocadillo-queso', 'Bocadillo de queso', 'Bocadillo con ficha alimentaria', 2.50, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80', '{"id":"bocadillo-queso","nombre":"Bocadillo de queso","categoria":"bocadillo","ingredientes":["pan blanco (harina de trigo, agua, levadura, sal)","queso gouda (leche de vaca pasteurizada, sal, fermentos lacticos, coagulante)"],"alergenos":["gluten","leche"],"trazas":["frutos de cascara"],"informacionNutricional":{"kcal":284.8,"grasas":8.13,"hidratos":40.93,"azucares":3.89,"proteinas":11.16,"sal":0.7},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT BOCADILLO DE QUESO JOSE ZERPA.odt","ETIQUETA BOCADILLO DE QUESO.docx"]}'::jsonb),
    ('bocadillo-tortilla-papas', 'Bocadillo de tortilla de papas', 'Bocadillo con ficha alimentaria', 2.50, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80', '{"id":"bocadillo-tortilla-papas","nombre":"Bocadillo de tortilla de papas","categoria":"bocadillo","ingredientes":["pan blanco (harina de trigo, agua, levadura, sal)","tortilla de papas (huevo, papas, sal, aceite)"],"alergenos":["gluten","huevo"],"trazas":[],"informacionNutricional":{"kcal":238.8,"grasas":4,"hidratos":42.34,"azucares":3.88,"proteinas":7.42,"sal":0.6},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT BOCADILLO DE TORTILLA DE PAPAS JOSE ZERPA.odt","ETIQUETA BOCADILLO DE TORTILLA DE PAPAS.docx"]}'::jsonb),
    ('bocadillo-tortilla-francesa', 'Bocadillo de tortilla francesa', 'Bocadillo con ficha alimentaria', 2.50, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80', '{"id":"bocadillo-tortilla-francesa","nombre":"Bocadillo de tortilla francesa","categoria":"bocadillo","ingredientes":["pan blanco (harina de trigo, agua, levadura, sal)","tortilla francesa (huevo, sal, aceite)"],"alergenos":["gluten","huevo"],"trazas":[],"informacionNutricional":{"kcal":247.2,"grasas":5.26,"hidratos":40.77,"azucares":3.73,"proteinas":8.66,"sal":0.74},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT BOCADILLO DE TORTILLA FRANCESA JOSE ZERPA.odt","ETIQUETA BOCADILLO DE TORTILLA FRANCESA.docx"]}'::jsonb),
    ('croissant-mixto', 'Croissant mixto', 'Croissant con ficha alimentaria', 1.80, 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80', '{"id":"croissant-mixto","nombre":"Croissant mixto","categoria":"croissant","ingredientes":["croissant (harina de trigo, harina de soja, margarina con grasa vegetal de palma, agua, aceite de girasol, emulgente e-471, sal, aromas, corrector de acidez e-330, colorante e-160a, agua, azucar, levadura, dextrosa, gluten de trigo, sal, emulgente e-472e, antiaglomerante e-170, almidon modificado, harina de soja, fructosa, espesante e-415, hidroxipol celulosa, agente de tratamiento de harina e-300, aroma, almidon de maiz, enzimas)","fiambre paleta cocida (carne de cerdo y pavo, agua, fecula de patata, sal, proteina de soja y leche, azucar, dextrosa, lactosa, aromas, antioxidante e-316, conservantes e-260, estabilizantes e-407 y e-451, potenciador del sabor e-621, colorante e-120)","queso gouda (leche de vaca pasteurizada, sal, fermentos lacticos, coagulante)"],"alergenos":["gluten","soja","leche"],"trazas":[],"informacionNutricional":{"kcal":375,"grasas":22.9,"hidratos":27.4,"azucares":2.1,"proteinas":10,"sal":1.6},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT CROISSANT MIXTO JOSE ZERPA.odt","ETIQUETA CROISSANT MIXTO.docx"]}'::jsonb),
    ('croissant-mixto-vegetal', 'Croissant mixto vegetal', 'Croissant con ficha alimentaria', 1.80, 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80', '{"id":"croissant-mixto-vegetal","nombre":"Croissant mixto vegetal","categoria":"croissant","ingredientes":["croissant (harina de trigo, harina de soja, margarina con grasa vegetal de palma, agua, aceite de girasol, emulgente e-471, sal, aromas, corrector de acidez e-330, colorante e-160a, agua, azucar, levadura, dextrosa, gluten de trigo, sal, emulgente e-472e, antiaglomerante e-170, almidon modificado, harina de soja, fructosa, espesante e-415, hidroxipol celulosa, agente de tratamiento de harina e-300, aroma, almidon de maiz, enzimas)","fiambre paleta cocida (carne de cerdo y pavo, agua, fecula de patata, sal, proteina de soja y leche, azucar, dextrosa, lactosa, aromas, antioxidante e-316, conservantes e-260, estabilizantes e-407 y e-451, potenciador del sabor e-621, colorante e-120)","queso gouda (leche de vaca pasteurizada, sal, fermentos lacticos, coagulante)","atun en aceite (atun, aceite de girasol, sal), maiz dulce (maiz, agua, azucar, sal), mayonesa (aceite de soja modificado geneticamente, agua, yema de huevo, jarabe de glucosa y fructosa, vinagre de vino, sal, almidon modificado de maiz e-1422, estabilizante e-415, conservador e-202, acidulante e-270, aroma, conservante e-385 (edta), colorante e-160a)","tomate","lechuga"],"alergenos":["gluten","soja","leche","pescado","huevo"],"trazas":[],"informacionNutricional":{"kcal":425,"grasas":27.3,"hidratos":29.4,"azucares":3.9,"proteinas":14.9,"sal":1.6},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT CROISSANT MIXTO VEGETAL JOSE ZERPA.odt","ETIQUETA CROISSANT MIXTO VEGETAL.docx"]}'::jsonb),
    ('croissant-vegetal', 'Croissant vegetal', 'Croissant con ficha alimentaria', 1.80, 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80', '{"id":"croissant-vegetal","nombre":"Croissant vegetal","categoria":"croissant","ingredientes":["croissant (harina de trigo, harina de soja, margarina con grasa vegetal de palma, agua, aceite de girasol, emulgente e-471, sal, aromas, corrector de acidez e-330, colorante e-160a, agua, azucar, levadura, dextrosa, gluten de trigo, sal, emulgente e-472e, antiaglomerante e-170, almidon modificado, harina de soja, fructosa, espesante e-415, hidroxipol celulosa, agente de tratamiento de harina e-300, aroma, almidon de maiz, enzimas)","atun en aceite (atun, aceite de girasol, sal), maiz dulce (maiz, agua, azucar, sal), mayonesa (aceite de soja modificado geneticamente, agua, yema de huevo, jarabe de glucosa y fructosa, vinagre de vino, sal, almidon modificado de maiz e-1422, estabilizante e-415, conservador e-202, acidulante e-270, aroma, conservante e-385 (edta), colorante e-160a)","tomate","lechuga"],"alergenos":["gluten","soja","pescado","huevo"],"trazas":[],"informacionNutricional":{"kcal":412,"grasas":23.2,"hidratos":26.3,"azucares":2.9,"proteinas":12.8,"sal":1.5},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT CROISSANT VEGETAL JOSE ZERPA.odt","ETIQUETA CROISSANT VEGETAL.docx"]}'::jsonb),
    ('sandwich-atun-millo-mayonesa', 'Sandwich de atun, millo y mayonesa', 'Sandwich con ficha alimentaria', 2.90, 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80', '{"id":"sandwich-atun-millo-mayonesa","nombre":"Sandwich de atun, millo y mayonesa","categoria":"sandwich","ingredientes":["pan de molde (harina de trigo, agua, sal, grasa vegetal, levadura, e-472e, e-300, enzima de panificar de trigo)","atun en aceite (atun, aceite de girasol, sal), maiz dulce (maiz, agua, azucar, sal), mayonesa (aceite de soja modificado geneticamente, agua, yema de huevo, jarabe de glucosa y fructosa, vinagre de vino, sal, almidon modificado de maiz e-1422, estabilizante e-415, conservador e-202, acidulante e-270, aroma, conservante e-385 (edta), colorante e-160a)"],"alergenos":["gluten","pescado","soja","huevo"],"trazas":[],"informacionNutricional":{"kcal":308.01,"grasas":20.05,"hidratos":20.1,"azucares":3.58,"proteinas":8.45,"sal":0.87},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT SANDWICH ATUN JOSE ZERPA.odt","ETIQUETA SANDWICH ATUN.docx"]}'::jsonb),
    ('sandwich-mixto', 'Sandwich mixto', 'Sandwich con ficha alimentaria', 2.90, 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80', '{"id":"sandwich-mixto","nombre":"Sandwich mixto","categoria":"sandwich","ingredientes":["pan de molde (harina de trigo, agua, sal, grasa vegetal, levadura, e-472e, e-300, enzima de panificar de trigo)","fiambre paleta cocida (carne de cerdo y pavo, agua, fecula de patata, sal, proteina de soja y leche, azucar, dextrosa, lactosa, aromas, antioxidante e-316, conservantes e-260, estabilizantes e-407 y e-451, potenciador del sabor e-621, colorante e-120)","queso gouda (leche de vaca pasteurizada, sal, fermentos lacticos, coagulante)"],"alergenos":["gluten","soja","leche"],"trazas":[],"informacionNutricional":{"kcal":279,"grasas":11.34,"hidratos":31.8,"azucares":3.53,"proteinas":12.3,"sal":1.91},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT SANDWICH MIXTO JOSE ZERPA.odt","ETIQUETA SANDWICH MIXTO.docx"]}'::jsonb),
    ('sandwich-vegetal', 'Sandwich vegetal', 'Sandwich con ficha alimentaria', 2.90, 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80', '{"id":"sandwich-vegetal","nombre":"Sandwich vegetal","categoria":"sandwich","ingredientes":["pan de molde (harina de trigo, agua, sal, grasa vegetal, levadura, e-472e, e-300, enzima de panificar de trigo)","atun en aceite (atun, aceite de girasol, sal), maiz dulce (maiz, agua, azucar, sal), mayonesa (aceite de soja modificado geneticamente, agua, yema de huevo, jarabe de glucosa y fructosa, vinagre de vino, sal, almidon modificado de maiz e-1422, estabilizante e-415, conservador e-202, acidulante e-270, aroma, conservante e-385 (edta), colorante e-160a)","tomate","lechuga"],"alergenos":["gluten","pescado","soja","huevo"],"trazas":[],"informacionNutricional":{"kcal":197,"grasas":15.5,"hidratos":18.5,"azucares":2.65,"proteinas":12,"sal":0.85},"conservacion":"consumo inmediato; refrigeracion entre 0 y 4 oC","caducidad":"consumir preferentemente antes de 24 horas","fuente":["FT SANDWICH VEGETAL JOSE ZERPA.odt","ETIQUETA SANDWICH VEGETAL.docx"]}'::jsonb)
), upserted AS (
  INSERT INTO products (name, description, price, image_url, product_info, is_active)
  SELECT name, description, price, image_url, product_info, true
  FROM source_products sp
  WHERE NOT EXISTS (
    SELECT 1 FROM products p WHERE p.product_info->>'id' = sp.slug OR lower(p.name) = lower(sp.name)
  )
  RETURNING id, product_info
), updated AS (
  UPDATE products p
  SET description = COALESCE(p.description, sp.description),
      image_url = COALESCE(p.image_url, sp.image_url),
      product_info = sp.product_info,
      is_active = true
  FROM source_products sp
  WHERE p.product_info->>'id' = sp.slug OR lower(p.name) = lower(sp.name)
  RETURNING p.id, p.product_info
)
SELECT COUNT(*) FROM upserted UNION ALL SELECT COUNT(*) FROM updated;

WITH source_allergens(slug, allergen_code) AS (
  VALUES
    ('bocadillo-atun-millo-mayonesa', 'GLUTEN'),
    ('bocadillo-atun-millo-mayonesa', 'FISH'),
    ('bocadillo-atun-millo-mayonesa', 'SOYBEANS'),
    ('bocadillo-atun-millo-mayonesa', 'EGGS'),
    ('bocadillo-jamon', 'GLUTEN'),
    ('bocadillo-jamon', 'SOYBEANS'),
    ('bocadillo-jamon', 'MILK'),
    ('bocadillo-jamon', 'TREE_NUTS'),
    ('bocadillo-jamon-serrano', 'GLUTEN'),
    ('bocadillo-lomo-adobado', 'GLUTEN'),
    ('bocadillo-lomo-adobado', 'SOYBEANS'),
    ('bocadillo-lomo-adobado', 'MILK'),
    ('bocadillo-pavo-cocido', 'GLUTEN'),
    ('bocadillo-pavo-cocido', 'SOYBEANS'),
    ('bocadillo-pechuga-plancha', 'GLUTEN'),
    ('bocadillo-queso', 'GLUTEN'),
    ('bocadillo-queso', 'MILK'),
    ('bocadillo-queso', 'TREE_NUTS'),
    ('bocadillo-tortilla-papas', 'GLUTEN'),
    ('bocadillo-tortilla-papas', 'EGGS'),
    ('bocadillo-tortilla-francesa', 'GLUTEN'),
    ('bocadillo-tortilla-francesa', 'EGGS'),
    ('croissant-mixto', 'GLUTEN'),
    ('croissant-mixto', 'SOYBEANS'),
    ('croissant-mixto', 'MILK'),
    ('croissant-mixto-vegetal', 'GLUTEN'),
    ('croissant-mixto-vegetal', 'SOYBEANS'),
    ('croissant-mixto-vegetal', 'MILK'),
    ('croissant-mixto-vegetal', 'FISH'),
    ('croissant-mixto-vegetal', 'EGGS'),
    ('croissant-vegetal', 'GLUTEN'),
    ('croissant-vegetal', 'SOYBEANS'),
    ('croissant-vegetal', 'FISH'),
    ('croissant-vegetal', 'EGGS'),
    ('sandwich-atun-millo-mayonesa', 'GLUTEN'),
    ('sandwich-atun-millo-mayonesa', 'FISH'),
    ('sandwich-atun-millo-mayonesa', 'SOYBEANS'),
    ('sandwich-atun-millo-mayonesa', 'EGGS'),
    ('sandwich-mixto', 'GLUTEN'),
    ('sandwich-mixto', 'SOYBEANS'),
    ('sandwich-mixto', 'MILK'),
    ('sandwich-vegetal', 'GLUTEN'),
    ('sandwich-vegetal', 'FISH'),
    ('sandwich-vegetal', 'SOYBEANS'),
    ('sandwich-vegetal', 'EGGS')
), matched_products AS (
  SELECT id, product_info->>'id' AS slug FROM products WHERE product_info ? 'id'
)
INSERT INTO product_allergens (product_id, allergen_id)
SELECT DISTINCT mp.id, a.id
FROM source_allergens sa
JOIN matched_products mp ON mp.slug = sa.slug
JOIN allergens a ON a.code = sa.allergen_code
ON CONFLICT (product_id, allergen_id) DO NOTHING;

COMMIT;